FROM perl:5.28-slim

RUN apt-get -y update && \
    apt-get install -y less vim iputils-ping && \
    apt-get install -y build-essential sudo libwww-perl && \
    apt-get install -y default-libmysqlclient-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN cpanm --notest Net::HTTP MogileFS::Server MogileFS::Utils DBD::mysql
